version: '3.9'

services:
  database:
    image: postgres:15-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: food
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "food"]
      interval: 10s
      retries: 5
      timeout: 10s

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    restart: always
    privileged: true
    ports:
      - "5672:5672"   # Porta padrão para conexões de aplicações
      - "15672:15672" # UI do RabbitMQ Management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin

  app:
    build:
      context: .
    ports:
      - "8082:8082"
    depends_on:
      database:
        condition: service_healthy
    environment:
      DB_HOST: database
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASS: postgres
      DB_BASE: food_production
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USER: admin
      RABBIT_PASS: admin
      PORT: 8082

volumes:
  postgres_data:
    driver: local
